ALTER TABLE inventario
  ADD COLUMN mostrar_sku BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN mostrar_categoria BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN mostrar_precio BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN mostrar_stock BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN mostrar_tipo BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN mostrar_medidas BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN mostrar_descripcion BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN mostrar_descripcion_detallada BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN mostrar_imagen BOOLEAN NOT NULL DEFAULT TRUE;
